name: Bug Report
description: Report a bug in TrustLock contracts or tests
title: "[BUG]: "
labels: ["bug", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug!
        
  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which component is affected?
      options:
        - trustlock-escrow contract
        - trustlock-factory contract
        - trustlock-traits contract
        - Test suite
        - Documentation
        - CI/CD
    validations:
      required: true
      
  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear description of what the bug is
      placeholder: What happened?
    validations:
      required: true
      
  - type: textarea
    id: reproduce
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce this issue?
      placeholder: |
        1. Deploy contract...
        2. Call function with...
        3. Observe error...
    validations:
      required: true
      
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
    validations:
      required: true
      
  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
    validations:
      required: true
      
  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Please provide environment details
      value: |
        - Clarinet version:
        - Node version:
        - OS:
        - Network (devnet/testnet/mainnet):
    validations:
      required: true
      
  - type: textarea
    id: logs
    attributes:
      label: Relevant Logs
      description: Include any error messages or logs
      render: shell
