name: Feature Request
description: Suggest a new feature for TrustLock
title: "[FEATURE]: "
labels: ["enhancement", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature!
        
  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which component would this affect?
      options:
        - Smart contracts
        - Testing infrastructure
        - Documentation
        - CI/CD
        - Developer tools
    validations:
      required: true
      
  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: I'm trying to... but I can't because...
    validations:
      required: true
      
  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe your proposed solution
    validations:
      required: true
      
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: What other solutions have you considered?
      
  - type: checkboxes
    id: breaking
    attributes:
      label: Breaking Change
      description: Would this be a breaking change?
      options:
        - label: This would be a breaking change
          required: false
          
  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context or screenshots
